### ISSUE TITLE
--remote-limit-api also filters local calls

### ISSUE THREAD

**Issue by project-Shift** [iotaledger/iri#54]
When IRI v 1.1.2.4 is started with the  --remote-limit-api  command line parameter, the commands are also being blocked even if the call comes form the local loopback interface:

`"COMMAND getNeighbors is not available on this node"` is received  when an explicit call is made to http://127.0.0.1:14265
The same behaviour happens if IPv6 is used http://[::1]:14265 or the usual moniker http://localhost:14265

The command filter should block access only to those requests coming from non-node ip addresses, right?

This could be OS-specific behaviour, as I only have tested it Windows.
IRI was directly compiled from source using maven 3.3.9 and JDK 1.8.121

**Comment by project-Shift** [comment]
![image](https://cloud.githubusercontent.com/assets/22128890/22184042/849835ea-e0c2-11e6-9a7f-665d09d488e1.png)

Example of output using unmodified console.html on Chrome running on the node

**Comment by project-Shift** [comment]
Just to make sure, here's the initiating command line:
`java -jar iri-1.1.2.4.jar -p 14265 -r 14265 --remote-limit-api "addNeighbors, removeNeighbors, getNeighbors, interruptAttachingToTangle, attachTotangle" --remote -e -n "....."`

**Comment by bahamapascal** [comment]
I can Confirm that this issue is not Windows specific. I experience the same problem on Ubuntu 16.04

**Comment by paulhandy** [comment]
Try with this branch:
https://github.com/iotaledger/iri/tree/fixRemoteApiLimit

**Comment by paulhandy** [comment]
Solved in https://github.com/iotaledger/iri/commit/c8a0d942be90eeb067edbbe00b878bc25a10d63b

**Comment by project-Shift** [comment]
Test with self-compiled jar and with jar provided by Paul, the issue remains, at least in Windows
Going to test further to make sure I'm not forgetting anything thing, but after testing with that last jar that was supplied, I'm pretty sure the issue is not solved in this situation

**Comment by paulhandy** [comment]
@project-Shift please provide the startup command you are using, as well as what API calls you are attempting, if they are different from above.

**Comment by project-Shift** [comment]
no, same startup as above; several tests again, all the outcomes are the same, call is blocked.

**Comment by bahamapascal** [comment]
I tested on Ubuntu 16.04 and successfully passed the getNeighbors API via localhost while remote call was blocked. Did not test on windows though

**Comment by project-Shift** [comment]
Also, I looked at you code, and although I'm not a dev, and don't know java, I would like to point out that in line 119, you might have used the actual loopback address instead of the "localhost" var
!sourceAddress.getAddress().equals(InetAddress.getByName("localhost")))
transforms into
!sourceAddress.getAddress().equals("127.0.0.1")) , at least just to diagnoze the fix?

The reason is simple: IPv6 , that happens to be active in my windows node
Localhost resolves to IPv6 loopback, which is [::1] , so I'm not sure how that comparison will work.


My humble apologies if it's a stupid suggestion, just trying to help out, even though clueless ...

**Comment by project-Shift** [comment]
Mean while, I'll try with IPv6 off ...

**Comment by paulhandy** [comment]
could you try tossing `            System.out.format("source:%s\tlocalhost:%s",sourceAddress.getAddress().toString(), InetAddress.getByName("localhost").toString());
` in line 118, and print out what the console debugger gives?

**Comment by project-Shift** [comment]
ups, not sure I quite follow those instructions :-/
Where and how should I do that?

**Comment by paulhandy** [comment]
Actually, try replacing
```
 !sourceAddress.getAddress().equals(InetAddress.getByName("localhost")))
```
 with the following:
```
                    !sourceAddress.getAddress().equals(InetAddress.getLocalHost()))
```

**Comment by project-Shift** [comment]
to the best of my current skill set, I looked up the api.java file in src, altered line 118 as per your request, did a new compile and packaging, replaced iri ... and the result is the same.

But these are uncharted waters for me! first time ever editing Java and 3th time only compiling ... so thread carefully :-D

**Comment by paulhandy** [comment]
> thread carefully
I see what you did there.

**Comment by project-Shift** [comment]
I did that on my local node, ofc, not on git

**Comment by project-Shift** [comment]
btw, also tried my stupid suggestion with the same results, so ...

**Comment by paulhandy** [comment]
What's in `C:\WINDOWS\system32\drivers\etc\hosts`?

**Comment by project-Shift** [comment]
definitely related to IPv6, it seems
I introduced sourceAddress.getAddress() and InetAddress.getByName("localhost") in the returned console message, to see what it was reading, and this is the result:
sourceAddress.getAddress()  = 0:0:0:0:0:0:0:1  <--- IPv6 loopback !!!
InetAddress.getByName("localhost") = localhost/127.0.0.1

I suposedly already disabled IPv6 in this node, but since it's a core version, I might be missing something.
Either way, this might explain why it's failing on my windows system

**Comment by paulhandy** [comment]
Try out this line.
```
                    !sourceAddress.getAddress().isLoopbackAddress()) {
```

**Comment by project-Shift** [comment]
ok, just got it to work with your initial fix :-)

In systems with IPv6 enabled, you must explicitly use 127.0.0.1 in your call, not localhost, because it's internally resolved to IPv6 loopback address, [::1]

Now, let's try that line of yours and see if we can make it universal :-)

**Comment by paulhandy** [comment]
Sorry I'm not really equipped for Windows testing at the moment... 😊

**Comment by project-Shift** [comment]
Confirmed solution!  Using powershell script, node js script, nostalgia.html and console.html, all working
using  !sourceAddress.getAddress().isLoopbackAddress()) {
becomes universally correct, even with IPv6 enabled, loopback is correctly identified and call can be made using the "localhost" moniker 👍 

Can you make the final adjustments and submit a new pull? Thanks a lot!
